Nop.Plugin.Payments.Bluefin/Controllers/PaymentBluefinController.cs
using System.Xml;
using System.Xml.Schema;
using System.Xml.Serialization;


using Microsoft.AspNetCore.Mvc;

using Newtonsoft.Json;

using Nop.Core;
using Nop.Core.Domain.Customers;
using Nop.Core.Domain.Logging;

using Nop.Plugin.Payments.Bluefin;
using Nop.Plugin.Payments.Bluefin.Domain;
using Nop.Plugin.Payments.Bluefin.Models;
using Nop.Plugin.Payments.Bluefin.Services;

using Nop.Services.Common;
using Nop.Services.Configuration;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Messages;
using Nop.Services.Orders;
using Nop.Services.Payments;
using Nop.Services.Security;

using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;

using Nop.Web.Framework.Mvc;
using Nop.Web.Framework.Mvc.Filters;

using Nop.Web.Areas.Admin.Models.Logging;

using Nop.Web.Framework.Models.Extensions;

using Nop.Web.Framework.Models;

using Nop.Web.Framework.Models.DataTables;


using Nop.Web.Areas.Admin.Models.Orders;
using Nop.Web.Areas.Admin.Factories;


using Nop.Core.Domain.Payments;
using Nop.Core.Domain.Orders;

using Nop.Core.Domain.Catalog;

using Microsoft.AspNetCore.Http;
using System.Dynamic;


using Nop.Services.Directory;

public partial record TraceLogsListModel : BasePagedListModel<TraceLogModel>
{
}

// [HttpsRequirement]
// [AutoValidateAntiforgeryToken]
// [ValidateIpAddress]
// [AuthorizeAdmin]
// [ValidateVendor]
public class PaymentBluefinController : BasePaymentController
{
    // private readonly ILogger _logger;
    private readonly ISettingService _settingService;
    private readonly ILocalizationService _localizationService;
    private readonly INotificationService _notificationService;
    protected readonly IOrderService _orderService;
    protected readonly IOrderModelFactory _orderModelFactory;
    private readonly IOrderProcessingService _orderProcessingService;
    private readonly IGenericAttributeService _genericAttributeService;

    private readonly BluefinPaymentSettings _bluefinPaymentSettings;
    private readonly IWorkContext _workContext;
    private readonly IStoreContext _storeContext;

    protected readonly IWebHelper _webHelper;
    protected readonly ICustomNumberFormatter _customNumberFormatter;

    private readonly BluefinGateway _gateway;

    private readonly BluefinTokenRepositoryService _bluefinTokenRepositoryService;
    private readonly TraceLogsRepositoryService _traceLogsRepositoryService;
    private readonly ReissueOrdersRepositoryService _reissueOrdersRepositoryService;

    private readonly IAddressService _addressService;


    private readonly IStateProvinceService _stateProvinceService;
    private readonly ICountryService _countryService;

    public PaymentBluefinController(ILogger logger,
        ISettingService settingService,
        ILocalizationService localizationService,
        INotificationService notificationService,
        IOrderService orderService,
        IOrderModelFactory orderModelFactory,
        IOrderProcessingService orderProcessingService,
        IGenericAttributeService genericAttributeService,
        BluefinPaymentSettings bluefinPaymentSettings,
        BluefinTokenRepositoryService bluefinTokenRepositoryService,
        ReissueOrdersRepositoryService reissueOrdersRepositoryService,
        TraceLogsRepositoryService traceLogsRepositoryService,
        IWorkContext workContext,
        IStoreContext storeContext,
        ICustomNumberFormatter customNumberFormatter,
        IAddressService addressService,
        IStateProvinceService stateProvinceService,
        ICountryService countryService,
        IWebHelper webHelper)
    {
        // _logger = logger;
        _localizationService = localizationService;
        _notificationService = notificationService;
        _orderService = orderService;
        _orderModelFactory = orderModelFactory;
        _settingService = settingService;
        _orderProcessingService = orderProcessingService;
        _storeContext = storeContext;
        _customNumberFormatter = customNumberFormatter;
        _bluefinPaymentSettings = bluefinPaymentSettings;
        _genericAttributeService = genericAttributeService;
        _bluefinTokenRepositoryService = bluefinTokenRepositoryService;
        _reissueOrdersRepositoryService = reissueOrdersRepositoryService;
        _traceLogsRepositoryService = traceLogsRepositoryService;
        _workContext = workContext;
        _addressService = addressService;
        _stateProvinceService = stateProvinceService;
        _countryService = countryService;
        _webHelper = webHelper;
        _gateway = new BluefinGateway(
            logger,
            _bluefinPaymentSettings,
            traceLogsRepositoryService
        );
    }

    [Area(AreaNames.ADMIN)]
    [CheckPermission(StandardPermission.Configuration.MANAGE_PAYMENT_METHODS)]
    public IActionResult TraceLogs() // async Task<IActionResult>
    {
        // var data = await _dbContext.BluefinEntries.ToListAsync();
        return View("~/Plugins/Payments.Bluefin/Views/TraceLogs.cshtml"); // , data);
    }

    [Area(AreaNames.ADMIN)]
    [CheckPermission(StandardPermission.System.MANAGE_SYSTEM_LOG)]
    public async Task<IActionResult> ViewTraceLog(int id)
    {
        var entry = await _traceLogsRepositoryService.GetById(id);

        var model = new TraceLogModel
        {
            Id = entry.Id,
            TraceId = entry.TraceId,
            ErrorMessage = entry.ErrorMessage,
            Json = entry.Json,
            Created = entry.Created
        };
        
        /*
        var log = await _logger.GetLogByIdAsync(id);
        if (log == null)
            return RedirectToAction("List");

        //prepare model
        var model = await _logModelFactory.PrepareLogModelAsync(null, log);
        */

        return View("~/Plugins/Payments.Bluefin/Views/ViewTraceLog.cshtml", model);
    }



    // [HttpPost]
    [Area(AreaNames.ADMIN)]
    [CheckPermission(StandardPermission.System.MANAGE_SYSTEM_LOG)]
    public async Task<IActionResult> TraceLogList(TraceSearchModel _searchModel)
    {

        // TODO: Refactor and optimize via query parameters for paged list with TraceSearchModel
        var _list = await _traceLogsRepositoryService.GetAllLogs();

        var __list = new List<TraceLogModel>();

        // TODO: Refactor to sort via query. This is inefficient
        var _sorted = new List<TraceIdEntry>(_list);

        // Descending
        _sorted.Sort((x,y) => y.Created.CompareTo(x.Created));

        foreach(var item in _sorted) {
            __list.Add(new TraceLogModel{
                Id = item.Id,
                TraceId = item.TraceId,
                ErrorMessage = item.ErrorMessage,
                Json = item.Json,
                Created = item.Created
            });
        }

        /*
        var _list = new List<TraceLogModel>
        {
             new TraceLogModel
            {
                Id = 0,
                TraceId = "c3abdb61-ca46-4cfc-8341-61ed69eee49a",
                ErrorMessage = "bfTokenReference is expired",
                Json = "{}"
            },
            new TraceLogModel
            {
                Id = 1,
                TraceId = "373fe421-bc7c-49c7-9a46-6d2d109fc3d8",
                ErrorMessage = "Request validation error: Does not conform to API schema.",
                Json = "{}"
            },
        };
        */


        // NOTE: Keep this commment if the functionality like this is needed down the line
        /*
        var searchModel = new TraceSearchModel
        {
            // TraceId = "A",
            // ErrorMessage = "B"
            Draw = "1"
        };
        */

        // Note: Page => (Start / Length) + 1; and PageSize => Length;
        var logItems = new PagedList<TraceLogModel>(__list, _searchModel.Page - 1, _searchModel.PageSize);

        // logItems.ToPagedList();

        var model = await new TraceLogsListModel().PrepareToGridAsync(_searchModel, logItems, () =>
        {
            //fill in model values from the entity
            return logItems.SelectAwait(async logItem =>
            {
                //fill in model values from the entity
                // var logModel = logItem.ToModel<TraceLogModel>();
                return logItem;
            });
        });

        /*
        return Json(new
        {
            Data = _sorted,
            draw = "1",
            recordsFiltered = _list.Count,
            recordsTotal = _list.Count,
            CustomProperties = new { }
        });
        */

        return Json(model);

        // return Json(new
        // {
        //    Data = _list
        // });

        // return Ok(new DataTablesModel { Data = _list });


    }


    [Area(AreaNames.ADMIN)]
    [CheckPermission(StandardPermission.Configuration.MANAGE_PAYMENT_METHODS)]
    public IActionResult ReissueOrders() // async Task<IActionResult>
    {
        // var data = await _dbContext.BluefinEntries.ToListAsync();
        return View("~/Plugins/Payments.Bluefin/Views/ReissueOrders.cshtml"); // , data);
    }

    [HttpPost]
    [Area(AreaNames.ADMIN)]
    [CheckPermission(StandardPermission.Orders.ORDERS_VIEW)]
    public async Task<IActionResult> OrderList(OrderSearchModel _searchModel)
    {
        //prepare model

        /*
        var searchModel = new OrderSearchModel{
            Draw = "1",
            // Page = _searchModel.Page,
        };
        */

        var model = await _orderModelFactory.PrepareOrderListModelAsync(_searchModel);

        return Json(model);
    }

    [Area(AreaNames.ADMIN)]
    [CheckPermission(StandardPermission.System.MANAGE_SYSTEM_LOG)]
    // [Route("ViewOrder/{order_temp_id}/{id}")]
    // [HttpGet("ViewOrder/{order_temp_id:long}/{id:int}")]
    public async Task<IActionResult> ViewOrder(int id) // long order_temp_id, int id
    {

        var order = await _orderService.GetOrderByIdAsync(id);

        // var model = await _orderModelFactory.PrepareOrderModelAsync(null, order);

Nop.Plugin.Payments.Bluefin/Views/PaymentInfo.cshtml
@model PaymentInfoModel


@{
    Layout = "";
    NopHtml.AddScriptParts(ResourceLocation.Head, BluefinPaymentDefaults.ScriptPath, excludeFromBundle: true);
    /*
    #bluefin-iframe-container {
        @if (Model.IframeResponsive)
        {
            <text>
            overflow: hidden;
            </text>
        }
    }
    */
}

<style>

    .custom-value {
        display: none !important;
    }

    #bluefin-iframe-container {
        width: 100%;
        min-height: 400px;
    }
    
    #bluefin-iframe-container iframe {
        border: none;
    }

    @if (Model.IframeResponsive) {
        <text>
            @@media screen and (width >= 1024px) {
                #bluefin-iframe-container iframe {
                    height: 700px;
                }
            }

            @@media screen and (max-width: 1024px) {
                #bluefin-iframe-container iframe {
                    height: 600px;
                }
            }
        </text>
    }


</style>

<input asp-for="IFrameCompleted" id="IFrameCompleted" type="hidden" />
<input asp-for="BfTokenReference" id="BfTokenReference" type="hidden" />
<input asp-for="BluefinPaymentType" id="BluefinPaymentType" type="hidden" />
<input asp-for="BfTransactionId" id="BfTransactionId" type="hidden" />
<input asp-for="BluefinSavePaymentOption" id="BluefinSavePaymentOption" type="hidden" />

<div id="bluefin-iframe-container"></div>

<script>
    // document.addEventListener("DOMContentLoaded", function() {
    ; (function () {

        const id = setInterval(() => {
            if (window.IframeV2 != null) {
                clearInterval(id)
                loadIframe()
            }
        }, 111)

        function isDigit(c) {
            return c >= '0' && c <= '9'
        }

        function removeCurrency(amount) { // Remove currency sign from the start from PrepareOrderTotalsModelAsync => OrderTotalsModel.orderTotal

            if (!isDigit(amount[0])) {
                let inx = -1
                for (let i = 1; i < amount.length; i++) {
                    if (isDigit(amount[i])) {
                        inx = i
                        break
                    }
                }
                return amount.slice(inx == -1 ? 0 : inx)

            } else if (!isDigit(amount[amount.length - 1])) {
                let inx = -1
                for (let i = amount.length - 2; i >= 0; i--) {
                    if (isDigit(amount[i])) {
                        inx = i
                        break
                    }
                }
                return amount.slice(0, inx + 1)
            }
            return amount

        }

        function parsePhoneNumber(phoneNumber) {
            let parsedPhoneNumber = ''
            phoneNumber = phoneNumber.replaceAll('&#x2B;', '')

            for(let c of phoneNumber) {
                if(isDigit(c)) parsedPhoneNumber += c
            }
            return parsedPhoneNumber
        }


        function loadIframe() {
            // if(window.BluefinIframe) return

            // window.BluefinIframe = true

            @{
                    // BillingAddress
                    var customer = await workContext.GetCurrentCustomerAsync();
                    var address = await addressService.GetAddressByIdAsync(customer.BillingAddressId ?? 0);
                    var stateProvince = await stateProvinceService.GetStateProvinceByAddressAsync(address);
                    var country = await countryService.GetCountryByAddressAsync(address);

                    // ShippingAddress
                    Address shipping_address = null;
                    StateProvince shipping_stateProvince = null;
                    Country shipping_country = null;

                    var shippingEnabled = false;

                    var store = await storeContext.GetCurrentStoreAsync();
                    var cart = await shoppingCartService.GetShoppingCartAsync(customer, ShoppingCartType.ShoppingCart, store.Id);

                    foreach(ShoppingCartItem cardItem in cart) {
                        var product = await productService.GetProductByIdAsync(cardItem.ProductId);
                        // NOTE: First Product in the cart to have shipping enabled wins
                        if(product.IsShipEnabled) {
                            shippingEnabled = true;
                            break;
                        }
                    }

                    if(shippingEnabled) {
                        shipping_address = await addressService.GetAddressByIdAsync(customer.ShippingAddressId ?? 0);
                        shipping_stateProvince = await stateProvinceService.GetStateProvinceByAddressAsync(shipping_address);
                        shipping_country = await countryService.GetCountryByAddressAsync(shipping_address);
                    }

                    var shopping_model = await shoppingCartModelFactory.PrepareOrderTotalsModelAsync(cart, false);


                    var pickupPoint = await genericAttributeService.GetAttributeAsync<PickupPoint>(customer,
                        NopCustomerDefaults.SelectedPickupPointAttribute, store.Id);

                    var currency = await workContext.GetWorkingCurrencyAsync();

                    var devServer = bluefinPaymentSettings.UseSandbox ? 
                        BluefinPaymentDefaults.CheckoutComponentCERT : BluefinPaymentDefaults.CheckoutComponentPROD;
                }

            const iframeConfig = {
                parentDivId: 'bluefin-iframe-container',
                width: '@(string.IsNullOrEmpty(Model.IframeWidth) ? "100%" : Model.IframeWidth)'
            }

            @if(!Model.IframeResponsive) {
                <text>
                    iframeConfig.height = '@(string.IsNullOrEmpty(Model.IframeHeight) ? "600px" : Model.IframeHeight)'
                </text>
            }

            if(!window.iframe_session) {
                window.iframe_session = {
                    start: Date.now()
                }
            }

            window.iframe_session.passed = Date.now() - window.iframe_session.start;

            let passed = parseInt(window.iframe_session.passed / 1000)

            let timeout = parseInt('@bluefinPaymentSettings.IframeTimeout') - passed;

            if(timeout <= 0) {
                alert("Iframe Payment Session Expired. Please, refresh the page and try again.")
                return
            }


            let shippingEnabled = '@shippingEnabled' == 'True'

            let customer = {
                Timeout: timeout,
                CustomerId: '@customer.Id',
                // TODO: Try to find the proper order total so that we don't have to do this
                Amount: removeCurrency('@shopping_model.OrderTotal'),
                Currency: '@currency.CurrencyCode',
                Email: '@address?.Email',
                BillingAddress: {
                    FirstName: '@address?.FirstName',
                    LastName: '@address?.LastName',
                    PhoneNumber: '+' + parsePhoneNumber('@address?.PhoneNumber'),
                    Address1: '@address?.Address1',
                    Address2: '@address?.Address2',
                    City: '@address?.City',
                    State: '@stateProvince?.Abbreviation',
                    Zip: '@address?.ZipPostalCode',
                    Company: '@address?.Company',
                    Country: '@country?.ThreeLetterIsoCode'
                }
            }

            if(shippingEnabled) {
                customer.ShippingAddress = {
                    FirstName: '@shipping_address?.FirstName',
                    LastName: '@shipping_address?.LastName',
                    PhoneNumber: '+' + parsePhoneNumber('@shipping_address?.PhoneNumber'),
                    Address1: '@shipping_address?.Address1',
                    Address2: '@shipping_address?.Address2',
                    City: '@shipping_address?.City',
                    State: '@shipping_stateProvince?.Abbreviation',
                    Zip: '@shipping_address?.ZipPostalCode',
                    Company: '@shipping_address?.Company',
                    Country: '@shipping_country?.ThreeLetterIsoCode'
                }
            }

            // Handle Pickup Address Information if selected by the user
            @if(pickupPoint != null) {
                <text>
                    let pickup_info = {
                        ShippingAddress: {
                            FirstName: '@pickupPoint?.Name',
                            Address1: '@pickupPoint?.Address',
                            City: '@pickupPoint?.City',
                            State: '@pickupPoint?.StateAbbreviation',
                            Zip: '@pickupPoint?.ZipPostalCode',
                            Country: '@pickupPoint?.CountryCode' // NOTE: two-letter ISO country code
                        }
                    }

                    // Overwrite
                    customer.ShippingAddress = pickup_info.ShippingAddress;

                </text>
            }

            // console.debug('customer:', shippingEnabled, customer)
            

            const callbacks = {
                iframeLoaded: function () {
                    // Bypass the nopCommerce default
                    let save_button = document.querySelector('button[onclick="PaymentInfo.save()"]')
                    save_button && save_button.remove()
                    console.debug('Iframe loaded')
                },
                checkoutComplete: async function (data) {
                    const iFrameCompleted = document.getElementById('IFrameCompleted')
                    const BfTokenReference_input = document.getElementById('BfTokenReference')

                    const BluefinPaymentType = document.getElementById('BluefinPaymentType')
                    const BluefinSavePaymentOption = document.getElementById('BluefinSavePaymentOption')

                    const bfTokenReference = data.bfTokenReference

                    const paymentType = data.data.type

                    try {
                        if (data.data.meta.savePaymentOption) {
                            BluefinSavePaymentOption && (BluefinSavePaymentOption.value = "Save Payment Credentials")
                        }

                    } catch (err) {
                        // TODO: Be more specific when returning error response text from the controller. This essentially just gives us the C# exception.
                        alert(err.toString())
                        return
                    }

                    BluefinPaymentType && (BluefinPaymentType.value = paymentType)


                    iFrameCompleted && (iFrameCompleted.value = 'Checkout Completed')
                    BfTokenReference_input && (BfTokenReference_input.value = bfTokenReference)

                    PaymentInfo.save()

                    // console.debug('Checkout complete:', data)
                },
                error: function (data) {
                    console.error('Error:', data)
                    // alert(JSON.stringify(data))
                },
                timeout: function (data) {
                    console.debug('Timeout:', data)
                },
            }

            // "Cache" the bearerToken in the current page so we keep keep the state of the checkout component after ValidatePaymentFormAsync
            // This also gets reused if the customer clicks on the "Back" button. However, there is one edge case where if we change the customer-related information by going back, the checkout component won't be recreated in the current page session.
            // if (!window.bearerToken) 
            {

            /*
            for(let message of (window.getEventListeners(window).message || [])) {
                if(window.IframeV2.init.toString().indexOf(message.listener.toString()) != -1) {
                    window.removeEventListener('message', message.listener)
                }
            }
            */
            
            $.ajax({
                    async: true,
                    type: 'POST',
                    url: '@(Url.Action("InitIframe", "PaymentBluefin"))',
                    data: customer,
                    success: function (data) {
                        const BfTransactionId = document.getElementById('BfTransactionId')

                        BfTransactionId && (BfTransactionId.value = data.transactionId)

                        window.bearerToken = data.bearerToken
                        window.IframeV2.init(iframeConfig,
                            data.bearerToken,
                            callbacks,
                            null,
                            '@devServer')
                    },
                    error: function (request, status, error) {
                        alert(request.responseText)
                    }
                })
            /*
            } else {
                window.IframeV2.init(iframeConfig,
                    window.bearerToken,
                    callbacks,
                    null,
                    '@devServer')

            }
            */
            }
        }
    
    })();


</script>

@NopHtml.GenerateScripts(ResourceLocation.Head)

Nop.Plugin.Payments.Bluefin/Views/TraceLogs.cshtml
@model TraceSearchModel

@{
    // ViewBag.PageTitle = "Bluefin Trace Logs";

    Layout = "_AdminLayout";
}


<div class="content-header clearfix">
    <h1 class="float-left">
        Bluefin Trace Logs
    </h1>
</div>

<div class="card card-default">
    <div class="card-body">

        @await Html.PartialAsync("Table", new DataTablesModel
        {
            Name = "log-grid",
            UrlRead = new DataUrl("TraceLogList", "PaymentBluefin", null),
            // SearchButtonId = "search-log",
            Length = 10,
            Paging = true,
            // Filters = new List<FilterParameter>
            //    {
                // new FilterParameter("CreatedOnFrom"),
                // new FilterParameter(nameof(Model.CreatedOnTo)),
                // new FilterParameter(nameof(Model.Message)),
                // new FilterParameter(nameof(Model.LogLevelId))
            //    },
            ColumnCollection = new List<ColumnProperty>
                {
                    new ColumnProperty(nameof(Model.TraceId))
                    {
                        // IsMasterCheckBox = true,
                        // Render = new RenderCheckBox("checkbox_log"),
                        // ClassName = NopColumnClassDefaults.CenterAll,
                        Title = "Trace Id",
                        Width = "50"
                    },
                    new ColumnProperty(nameof(Model.ErrorMessage))
                    {
                        Title = "Error Message", // T("Admin.System.Log.Fields.LogLevel").Text,
                        Width = "100"
                    },
                    new ColumnProperty(nameof(Model.Created))
                    {
                        Title = "Occurred", // T("Admin.System.Log.Fields.LogLevel").Text,
                        Width = "100"
                    },
                    new ColumnProperty(nameof(Model.Id))
                    {
                        Title = "View", // T("Admin.Common.View").Text,
                        Width = "50",
                        ClassName =  NopColumnClassDefaults.Button,
                        Render = new RenderButtonView(new DataUrl("~/Admin/PaymentBluefin/ViewTraceLog"))
                    }
                }
        })
    </div>
</div>

Nop.Plugin.Payments.Bluefin/Views/ViewOrder.cshtml
@model ReissueOrderModel

@{
    // ViewBag.PageTitle = "Bluefin Reissue Orders";

    Layout = "_AdminLayout";
}

<form asp-controller="PaymentBluefin" asp-action="EditOrder" method="post" asp-route-id="@Model.Id">
    <div class="content-header clearfix">
        <h1>
            Order Details
            <small>
                <i class="fas fa-arrow-circle-left"></i>
                <a asp-action="ReissueOrders">Back to Bluefin Reissue Orders</a>
            </small>
        </h1>
    </div>

    <section class="content">
        <div class="container-fluid">
            <div class="form-horizontal">
                <div class="cards-group">
                    <div class="card card-default">
                        <div class="card-body">

                            <blockquote>
                                <p>
                                <p style="line-height: 0;">
                                    To add products to the newly reissued order after applying the order amonts, go to Sales -> Orders with the reissued order id, click on View scroll down to Products and Add Products.
                                </p>
                                <br/>
                                
                                <p style="line-height: 0;">
                                    Please, make sure that the order amounts total matches the total of products added.
                                    It is optimal that the merchant uses their own generic products to specify the purpose or details of the additional charge.
                                </p>

                                <br/>

                                <p style="line-height: 0;">
                                    The shipping and billing address is based on the previous/initial order.
                                </p>

                                For more details on reissuing orders, make sure to check out the following documentation with our step-by-step tutorial
                                <a href="https://developers.bluefin.com/payconex/v4/reference/nopcommerce-plugin-for-bluefin#reissue-orders-component"
                                    target="_blank" rel="noopener noreferrer">
                                    nopCommerce Plugin for Bluefin | Reissue Orders Component
                                </a>
                                </p>
                            </blockquote>

                            <div class="form-group row">
                                <div class="col-md-3">
                                    <nop-label asp-for="Id" />
                                </div>
                                <div class="col-md-9">
                                    <div class="form-text-row">@Model.Id</div>
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-md-3">
                                    <nop-label asp-for="OrderStatus" />
                                </div>
                                <div class="col-md-9">
                                    <div class="form-text-row">@Model.OrderStatus</div>
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-md-3">
                                    <nop-label asp-for="OrderGuid" />
                                </div>
                                <div class="col-md-9">
                                    <div class="form-text-row">@Model.OrderGuid</div>
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-md-3">
                                    <nop-label asp-for="PaymentStatus" />
                                </div>
                                <div class="col-md-9">
                                    <div class="form-text-row">@Model.PaymentStatus</div>
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-md-3">
                                    <nop-label asp-for="OrderTotal" />
                                </div>
                                <div class="col-md-9">
                                    <div class="form-text-row">@Model.OrderTotal</div>
                                </div>
                            </div>
                        

                            <div class="form-group row">
                                <div class="col-md-3">
                                    <nop-label asp-for="ReissueTotal" />
                                </div>
                                <div class="col-md-9">
                                    <nop-editor asp-for="ReissueTotal" asp-required="true" />
                                </div>
                            </div>



                            @*
                            <div>
                                <input name="_AAA" id="_AAA" type="hidden" />
                            </div>
                            *@


                            <div class="form-group row">
                                <div class="col-md-9 offset-md-3">
                                    <button type="submit" name="reissueorder" id="reissueorder" class="btn btn-primary">
                                        Reissue Order
                                    </button>
                                    <text>&nbsp;</text>
                                    <nop-action-confirmation asp-button-id="reissueorder" />
                                </div>
                            </div>


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <script>
        ; $(document).ready(function () {


        });

    </script>

</form>